# Generated by Django 6.0.8 on 2026-08-05 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booked_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="tickets_count",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(default="Booked", max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="tickets",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
