# Generated by Django 6.0.8 on 2026-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_remove_booking_booked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
